create table if not exists public.products (
 id bigint generated by default as identity primary key,
 name text not null,
 description text default '',
 price numeric(12,2) not null,
 created_at timestamptz default now()
);

create table if not exists public.orders (
 id bigint generated by default as identity primary key,
 user_id uuid,
 customer_name text not null,
 email text not null,
 address text not null,
 total numeric(12,2) not null,
 items jsonb not null,
 created_at timestamptz default now()
);

alter table public.products enable row level security;
alter table public.orders enable row level security;

drop policy if exists "products are public" on public.products;
create policy "products are public" on public.products for select using (true);

drop policy if exists "orders can be inserted" on public.orders;
create policy "orders can be inserted" on public.orders for insert with check (true);

insert into public.products (name,description,price)
select * from (values
 ('Classic T-Shirt','Comfortable everyday shirt',12000),
 ('Premium Hoodie','Warm premium hoodie',25000),
 ('Canvas Bag','Simple reusable shopping bag',8000)
) as v(name,description,price)
where not exists (select 1 from public.products);